# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Paysikka' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Paysikka


pod 'VegaScrollFlowLayout'
pod 'SwiftMessages'
pod 'IQKeyboardManagerSwift'
pod 'Tabman', '~> 2.13'
pod 'XLPagerTabStrip', '~> 9.0'
pod 'Parchment', '~> 3.2'


end
